### ISSUE TITLE
Fetching Data From Server Side Basic

### ISSUE THREAD

**Issue by muzzy28** [yohangz/ornamentum#25]
Hi,
I'm triying to fetch data from web service. I tried Server Side Basic steps which are in your documents.
However, I could'nt bind data from web service to datatable.
My question is that do you have detail sample of fetching data from server side operations.

Thank you in advance

**Comment by aravindakr** [comment]
Hi muzzy,
Documentations are clearly mention what are the requirements for basic server side binding for both components. However, could you please more descriptive? or drop us a sample code snippet. so then we can help to resolve your problem. 🙂

Thank You

**Comment by muzzy28** [comment]
Hi aravindakr,

For example, I'm doing a request with HttpRequestOptions  object as above.
However, I can't see header object in request when I look network on browser.
Already response comes 401 as it's supposed to be
 
**const reqOptions: HttpRequestOptions = {
    url: 'myUrl',
    headers: {
        Authorization: 'myAuthorization'
    }
 };
 this.onDataBind = this.dataFetchService.onDataBind(reqOptions);**

**Comment by yohangz** [comment]
Please use the latest version of Ornamentum (3.2.1) to resolve this issue. 

There was a bug in DataTableHttpResourceService options parser.

**Comment by muzzy28** [comment]
Thank you  for reply.
When can we reach latest verison.
I coudn't get with yarn and npm yet.

**Comment by yohangz** [comment]
Just published the latest version to NPM.
