### ISSUE TITLE
How to use mapper oblect in onDataBind 

### ISSUE THREAD

**Issue by muzzy28** [yohangz/ornamentum#26]
Hi,

I need to map response of Server Side Basic Data Binding and I searched documentation
Is there sample usage of mapper object in onDataBind?

Thank you

**Comment by muzzy28** [comment]
Hi,

Is there sample usage of mapper object in onDataBind?

Thank you

**Comment by yohangz** [comment]
Mapper argument is a function and its signature is `(response: Observable<Q>) => Observable<DataTableQueryResult<T[]>>`

```
this.onDataBind = this.dataFetchService.onDataBind('/api/data', (response: Observable<any>): Observable<DataTableQueryResult<any[]>> => {
      return response.pipe(
        map((data) => {
          // your data mapping logic goes here
          return {
            count: data.nested.total,
            items: data.nested.items
          };
        })
      );
    });
```

Mapper function will get the source data observable which has data from your service and you should map it to the data table target format which is `DataTableQueryResult`. You can use any RxJS operator and whatever the mapping logic to populate data table supported schema compliant data.

We are still working on the documentation and it is not documented yet. However, you can have a look at the implementation details to find more insights on how to use for the time being.

https://ornamentum.app/api-docs/injectables/DataTableHttpDataFetchService.html#source
