### ISSUE TITLE
How to use custom service call with pagination

### ISSUE THREAD

**Issue by muzzy28** [yohangz/ornamentum#27]
Hi,

In our project, we have  our custom service call mechanism(interceptors, token operations etc.) and also we can get pagination informations from service calls.
My question is that I want to get datas from my service mechanism then I want apply these datas to table component with pagination.
My sample codes as below

   **interface MySampleInterface{
        items: <T>[];
        count: number;
    }**

  **@Component({
  })
  export class SampleComponent {
     tableData: MySampleInterface;
    constructor(private dataFetchService: MyServiCallMechanism<ExampleData>) {
      // this mechanism gets 10 datas of first page from service 
      this.tableData = this.dataFetchService.onDataBind('/api/resource/path?limit=10&offset=0');
    }
  }**
After these operations in view, I want to use tableData like this with pagination.
However, how can we use appy total page to datatable
 **<ng-data-table
    [items]="tableData.items">
  </ng-data-table>**

**Comment by yohangz** [comment]
@muzzy28 You have to use server-side pagination for this purpose as your service is a  server-side paginated API. Please refer to[ server-side basic data binding](https://ornamentum.app/feature/data-table/data-binding/server-side/basic) documentation.

`DataTableHttpDataFetchService` will make the paginated API calls for you when you use `onDataBind` callback input binding.

```
import { Component } from '@angular/core';
 
import { DataTableHttpDataFetchService, DataTableDataBindCallback } from 'ornamentum';
 
import { ExampleData } from 'helper-models';
 
@Component({
  selector: 'app-server-side-basic-usage',
  templateUrl: './server-side-basic-usage.component.html'
})
export class ServerSideBasicUsageComponent {
  public onDataBind: DataTableDataBindCallback;
 
  constructor(private dataFetchService: DataTableHttpDataFetchService<ExampleData>) {
    this.onDataBind = this.dataFetchService.onDataBind('/api/resource/path');
  }
}
```
