### ISSUE TITLE
custom function  for column will be better 

### ISSUE THREAD

**Issue by ranglang** [yohangz/ornamentum#28]

**Comment by yohangz** [comment]
Please provide more context

**Comment by ranglang** [comment]
> Please provide more context

sorry for unclear question,  thanks for response

```
  <ng-data-table-column
    [field]="'holdMoney'"
    [title]="'holdMoney'"
    [sortable]="true"
    [width]="20">
  </ng-data-table-column>
```
I found make column (number type) is  sorted by lexical order, as the following, not  min-max sort.
![1555517405619](https://user-images.githubusercontent.com/12862508/56303395-6462bc80-616e-11e9-91aa-9689b37e370f.jpg)


so i'm thinking...
can i just pass sort function as the following.

const sortBy = (a, b ) =>  b -a
```
<ng-data-table-column
    [field]="'holdMoney'"
    [title]="'holdMoney'"
    [sortable]="true"
[sortBy]="sortBy"
    [width]="20">
  </ng-data-table-column>
```

**Comment by aravindakr95** [comment]
Hi ranglang,
currently we do not supports for lexical ordering and there is no custom callback function for sorting operations.

Thank You.

Regards,
Aravinda Rathnayake

**Comment by yohangz** [comment]
@ranglang number sorting is already supported by Ornamentum data table. Please check whether your data set has those number values in **number** type or **string** type. It will only work if you have the values in **number** type.

**Comment by ranglang** [comment]
yes, you are right, i make a mistake @yohangz
