### ISSUE TITLE
How to reload onDataBind 

### ISSUE THREAD

**Issue by zyn926** [yohangz/ornamentum#29]
Using the "onDataBind" when I modify the data need to reload the data, how to reload，thanks

**Comment by aravindakr95** [comment]
Hi Zyn926,

Your question is not clear. Can you share the code snippet used to bind data. Also, which component are you using (data table or dropdown)? Please elaborate further on what you are trying to do?  

Thanks.

**Comment by zyn926** [comment]
I use a data table to display the data，but I have gain change operation on data，after I want to modify the data and reload the data.
  ngOnInit() {
    this.getListData();
  }

  getListData() {
    this.onDataBind = this.dataFetchService.onDataBind('http://localhost:8080/api/staff/getStaffList');
  }

  addOrEdit(_staff) {
    const dia = this.dialog.open(StaffAddOrEditComponent, {
      minWidth: 400,
      data: _staff ? _staff : null
    });
    dia.afterClosed().subscribe((res) => {
      if (res) {
        this.getListData();
      }
    });
  }

**Comment by zyn926** [comment]
> Hi Zyn926,
> 
> Your question is not clear. Can you share the code snippet used to bind data. Also, which component are you using (data table or dropdown)? Please elaborate further on what you are trying to do?
> 
> Thanks.

I use a data table to display the data，but I have gain change operation on data，after I want to modify the data and reload the data.
ngOnInit() {
this.getListData();
}

getListData() {
this.onDataBind = this.dataFetchService.onDataBind('http://localhost:8080/api/staff/getStaffList');
}

addOrEdit(_staff) {
const dia = this.dialog.open(StaffAddOrEditComponent, {
minWidth: 400,
data: _staff ? _staff : null
});
dia.afterClosed().subscribe((res) => {
if (res) {
this.getListData();
}
});
}
This is part of the code，I should how to reload data

Thanks

**Comment by aravindakr95** [comment]
There are multiple approaches to bind data for data table. refer the [https://ornamentum.app/feature/data-table/data-binding/client-side/basic](client-side basic data binding) and follow the provided instructions. further, if you have any concerns please let me know.

**Comment by zyn926** [comment]
> There are multiple approaches to bind data for data table. refer the [client-side basic data binding](https://ornamentum.app/feature/data-table/data-binding/client-side/basic) and follow the provided instructions. further, if you have any concerns please let me know.
User“this.dataFetchService.onDataBind('');” Data binding only once？Here the data I need paging on the server,are there any other method call paging component？

Thanks

**Comment by zyn926** [comment]
> There are multiple approaches to bind data for data table. refer the [client-side basic data binding](https://ornamentum.app/feature/data-table/data-binding/client-side/basic) and follow the provided instructions. further, if you have any concerns please let me know.

User“this.dataFetchService.onDataBind('');” Data binding only once？Here the data I need paging on the server,are there any other method call paging component？

**Comment by zyn926** [comment]
Hi
Can I use DataTableEventStateService？
If I can call should be how to call？
Thanks

**Comment by aravindakr95** [comment]
> > There are multiple approaches to bind data for data table. refer the [client-side basic data binding](https://ornamentum.app/feature/data-table/data-binding/client-side/basic) and follow the provided instructions. further, if you have any concerns please let me know.
> 
> User“this.dataFetchService.onDataBind('');” Data binding only once？Here the data I need paging on the server,are there any other method call paging component？

If you want to perform server-side pagination use [server-side basic data binding](https://ornamentum.app/feature/data-table/data-binding/server-side/basic) and follow the provided instructions. do not mess with internal services with user exposed functionalities. :)

**Comment by zyn926** [comment]
> > > There are multiple approaches to bind data for data table. refer the [client-side basic data binding](https://ornamentum.app/feature/data-table/data-binding/client-side/basic) and follow the provided instructions. further, if you have any concerns please let me know.
> > 
> > 
> > User“this.dataFetchService.onDataBind('');” Data binding only once？Here the data I need paging on the server,are there any other method call paging component？
> 
> If you want to perform server-side pagination use [server-side basic data binding](https://ornamentum.app/feature/data-table/data-binding/server-side/basic) and follow the provided instructions. do not mess with internal services with user exposed functionalities. :)

I use server-side paging, how to reload this data, such as I added a new data, how to load this data into the table？
Thanks
