### ISSUE TITLE
Custom template for options in filterable table column

### ISSUE THREAD

**Issue by pschild** [yohangz/ornamentum#42]
Hi guys,

in the documentation I saw that it's possible to define a custom Option Template for options in **Ornamentum Dropdown** [(see documentation)](https://ornamentum.app/feature/dropdown/templating/option-template)

Is this also possible for the options that are shown for a filterable column, using [Filter Dropdown](https://ornamentum.app/feature/data-table/functionality/column/filtering#filterDropdown)?

Background: I'd like to show some additional info behind the different filter options, something like
```
[ ] Value 1 (foo)
[ ] Value 2 (bar)
```

Cheers!

**Comment by yohangz** [comment]
Hi @pschild, 

Data table dropdown filter template customization is not yet supported. However, you can use all other dropdown features within data table component. I will consider this a feature request.

Thanks and Regards,
Yohan
