### ISSUE TITLE
Configuration of translations not available for all texts

### ISSUE THREAD

**Issue by pschild** [yohangz/ornamentum#45]
Hi!
I'm using the framework within an app for german users. Unfortunately, translations cannot completely be configured for all of the text snippets. Here's a list of texts that still appear in english and are hardcoded within the HTML templates:
* _Pagination:_ Ergebnisse: 1-10 **of** 42
* _Column Selection:_ **Show/Hide Column**
* _Tooltips for buttons:_ **First Page**, **Previous Page**, **Next Page**, **Last Page**, **Select Column**
* _Dropdowns:_ When using Dropdown Filtering (`[showDropdownFilter]="true"`), translations for dropdowns seem not to be passed to the nested components, so I have no option to configure translations for `filterPlaceholder`, `selectPlaceholder` and `selectedOptionWrapPlaceholder`.

Maybe you could make this possible :-)

Best regards,
pschild

**Comment by yohangz** [comment]
@pschild, we can fix the above mentioned and enhance localization. We will plan to push a release with the fixes ASAP.

**Comment by cagline** [comment]
[Update documentation with newly added translatable configurations](https://github.com/yohangz/ornamentum/commit/12c2810841a2459f00393741b243d2769e4bcbe1)
